### ISSUE TITLE
Feature request: ability to mark test failures as expected

### ISSUE THREAD

**Issue by twpayne** [mattfenwick/cyclonus#1]
Cilium currently does not pass all of cyclonus's tests (https://github.com/cilium/cilium/issues/14678), and as cyclonus's test suite expands Cilium might fail other tests due to [missing features in Cilium's `NetworkPolicy` implementation](https://docs.cilium.io/en/v1.9/concepts/kubernetes/policy/#k8s-policy).

So that cyclonus can be used in Cilium's CI (which requires all tests to pass before a PR can be merged), it would be nice if individual tests could be marked as "expected to fail". For these tests, cyclonus should still run them, but report success if they fail and failure if they succeed. This allows CI to pass for known failures, and will alert developers to update the cyclonus test configuration if/when Cilium fixes the bug.

Marking individual tests as "expected to fail" could either be done through a CLI option or a configuration file, depending on the number of tests expected to fail.

**Comment by mattfenwick** [comment]
@twpayne great suggestion, I've been thinking about this!

Maybe we'll come up something better, but to get started here's a couple ideas, we can iterate on this if necessary:

1. assuming a fixed set of test cases -- simply number them 1 - n, and let cases to skip be passed in through config or CLI flags.  Advantages: simple, easy, no strange failure cases 😄 , can get that set up quickly.  Disadvantages: only works with fixed set of tests, annoying to have to curate a list of case numbers.

2. label tests by the network policy features (or corner cases?  or something?)  they use and flag any test case including that netpol fragment.  Advantages: works with changing set of test cases, better connection between "list of things to ignore" and "test cases that fail".  Disadvantages: more complicated, might have unexpected behavior in some cases.

**Comment by twpayne** [comment]
Your proposal 2 sounds much more robust to me, I agree with you that option 1 would quickly become unmanageable.

Maybe each test could have a name of the format `testName:source:destination`, something like `ingress:x/a:x/a` or `egress:x/c:z/a` and then use a list of filters with wildcards to match them, e.g. `ingress:x/a:*` to match all ingress tests from x/a or `egress:**` to match all egress tests. A command line flag could then be something like `--expect-fail=ingress:x/a/:*`.

This would be extensible to new test names and new sources and destinations, be stable as new tests are added, and be relatively human readable.

**Comment by twpayne** [comment]
Closing as stale.
