### ISSUE TITLE
get a single connectivity matrix to fit on a single page (even on smaller monitors)

### ISSUE THREAD

**Issue by mattfenwick** [mattfenwick/cyclonus#106]
Connectivity matrices with multiple ports and protocols expand vertically and can quickly take more than a single screen of space.

It's really useful to see the whole thing at once!

**Comment by cdtomkins** [comment]
There were two comments to make this happen - one would be to use [block elements](https://en.wikipedia.org/wiki/Block_Elements), through something like https://github.com/eliukblau/pixterm

The other, if I understood correctly, was to switch the X/Y axis of the table as characters are taller than they are wide.
