### ISSUE TITLE
UX: Rename fuzz command to generate

### ISSUE THREAD

**Issue by twpayne** [mattfenwick/cyclonus#3]
cyclonus currently has a `fuzz` command that is described as:

> Generate network policies, install the policies one at a time in kubernetes, and compare actual measured connectivity to expected connectivity using a truth table.

Fuzzing is [described by Wikipedia](https://en.wikipedia.org/wiki/Fuzzing) as:

> Fuzzing or fuzz testing is an automated software testing technique that involves providing invalid, unexpected, or random data as inputs to a computer program.

Since `generate` is a more accurate description of what the `fuzz` command currently does, would it make sense to rename the command from `fuzz` to `generate`?

**Comment by mattfenwick** [comment]
👍 agreed!

**Comment by mattfenwick** [comment]
Done in https://github.com/mattfenwick/cyclonus/commit/2efc8eba4f738e653b1c6a580cf6f1705b0afb30
