### ISSUE TITLE
collect cyclonus data across a variety of clusters and CNIs

### ISSUE THREAD

**Issue by mattfenwick** [mattfenwick/cyclonus#46]
Procedure:

 - spin up cluster with a CNI
 - [run cyclonus job](https://github.com/mattfenwick/cyclonus#run-as-a-kubernetes-job)
   - check out https://github.com/mattfenwick/cyclonus/tree/master/jobs -- notice the different arguments for each CNI, this is because of their differences in support for some features
 - capture:
    - cyclonus invocation
    - cyclonus job logs
    - all cluster info (version, ip version, etc.)
    - all CNI info (config, version, etc.)

**IPV4 Progress table:**

KinD:
| CNI | Version | Linux | Windows | 
| --- | --- | --- | --- |
| Calico |  v3.18.0 | ✅ | ❌ |
| Calico |  v3.18.1 | ❌ | ❌ |
| Antrea |  v0.12.0 | ✅ | ❌ |
| Antrea |  v0.12.2 | ✅ | ❌ |
| Cilium |  v1.9.4 | ✅ | ❌ |
| Cilium |  v1.9.5 | ✅ | ❌ |
| Weave | ??? | ❌ | ❌ |
| ovn-kubernetes | ??? | ✅ | ❌ |

Azure:
| CNI | Version | Linux | Windows | 
| --- | --- | --- | --- |
| Calico |  v3.18.1 | ❌ | ❌ |

GKE:
| CNI | Version | Linux | Windows | 
| --- | --- | --- | --- |
| Calico |  v3.18.0 | ✅ | ❌ |
| Antrea |  v0.12.2 | ❌ | ❌ |
| Cilium |  v1.9.5 | ✅ | ❌ |
| ovn-kubernetes | ??? | ❌ | ❌ |

EKS:
| CNI | Version | Linux | Windows | 
| --- | --- | --- | --- |
| Calico |  v3,18.0 | ❌ | ❌ |
| Antrea |  v0.12.2 | ❌ | ❌ |
| Cilium |  v1.9.5 | ❌ | ❌ |
| ovn-kubernetes | ??? | ❌ | ❌ |

Partial data:

 - weave on KinD (pending verification from @dougsland @rikatz)

Network policies not supported, so don't need data:

 - Flannel

**IPV6 is not yet supported by Cyclonus**

## Bugs reported

 - Calico bug: https://github.com/projectcalico/libcalico-go/pull/1370
 - Antrea bug: https://github.com/vmware-tanzu/antrea/issues/1764
 - Cilium bug: https://github.com/cilium/cilium/pull/14720
 - Antrea CI https://github.com/vmware-tanzu/antrea/pull/1765
 - Cilium CI https://github.com/cilium/cilium/pull/14889
 - ovn missing named port support: https://github.com/ovn-org/ovn-kubernetes/issues/2117

**Comment by dougsland** [comment]
@mattfenwick looking to provide logs via KinD. I have bunch of machines here.

**Comment by dougsland** [comment]
Attached files from antrea, calico, cilium.

[output-antrea-testing-Mar-7-2021.log.gz](https://github.com/mattfenwick/cyclonus/files/6105617/output-antrea-testing-Mar-7-2021.log.gz)
[output-calico-testing-Mar-7-2021.log.gz](https://github.com/mattfenwick/cyclonus/files/6105618/output-calico-testing-Mar-7-2021.log.gz)
[output-cilium-testing-Mar-8-2021.log.gz](https://github.com/mattfenwick/cyclonus/files/6105619/output-cilium-testing-Mar-8-2021.log.gz)

**Comment by dougsland** [comment]
Antrea v0.12.2 with additional files about the env and triggering.
[kind-output-antrea-v0.12.2.tar.gz](https://github.com/mattfenwick/cyclonus/files/6125816/kind-output-antrea-v0.12.2.tar.gz)

**Comment by dougsland** [comment]
Cilium v1.9.5 data
[v1.9.5-cilium-output.tar.gz](https://github.com/mattfenwick/cyclonus/files/6126673/v1.9.5-cilium-output.tar.gz)

**Comment by dougsland** [comment]
[weavenet-output-Mar14-2021.tar.gz](https://github.com/mattfenwick/cyclonus/files/6141736/weavenet-output-Mar14-2021.tar.gz)

**Comment by mattfenwick** [comment]
More results from @dougsland and @rikatz:

[gke-calico1.log.gz](https://github.com/mattfenwick/cyclonus/files/6156650/gke-calico1.log.gz)
[gke-cilium.log.gz](https://github.com/mattfenwick/cyclonus/files/6156652/gke-cilium.log.gz)
[output-weavenet-Mar-13-2021.tar.gz](https://github.com/mattfenwick/cyclonus/files/6156654/output-weavenet-Mar-13-2021.tar.gz)

**Comment by mattfenwick** [comment]
ovn-kubernetes from @dougsland :

[output-ovn-kubernetes.tar.gz](https://github.com/mattfenwick/cyclonus/files/6156660/output-ovn-kubernetes.tar.gz)

**Comment by mattfenwick** [comment]
ovn-kubernetes https://github.com/mattfenwick/cyclonus/runs/2130448921?check_suite_focus=true

**Comment by mattfenwick** [comment]
🎉 Moved to https://github.com/K8sbykeshed/cyclonus-artifacts 🎉
